name: ESP32 Matter CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Phase 1: Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4


    - name: Install ESP-IDF
      run: |
        sudo apt update
        sudo apt install -y git wget curl build-essential cmake ninja-build python3 python3-pip python3-venv unzip
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
        . ./export.sh
   # Phase 3: Install ESP-Matter
     - name: Install ESP-Matter
       run: |
         git clone --recursive https://github.com/espressif/esp-matter.git
         cd esp-matter

    # Ensure all submodules are fully initialized
         git submodule update --init --recursive

    # Export environment
         echo "ESP_MATTER_PATH=$PWD" >> $GITHUB_ENV
     

    # Phase 4: Build firmware
    - name: Build firmware
      run: |
        idf.py set-target esp32c3
        idf.py build

    # Phase 5: Upload firmware (.bin)
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/*.bin
